### ISSUE TITLE
Embed the live twitter feed into the site

### ISSUE THREAD

**Issue by magician03** [fossiiita/humblefoolcup#11]

**Comment by pranayyelugam** [comment]
where do we need to embed this? . It will be a lot better if you guys modify the index.html to show the participants where you the changes to be done . For suppose , there's a issue to upload the stats for last year humblefoolcup but where do you need it ? you should tell the participants where they have to do changes .

**Comment by magician03** [comment]
@pranayyelugam , this need to be embedded in the site when project kicks off with some other issues, which right now isn't yet started. We appreciate your participation and enthusiasm and request you to work upon the issue that you started earlier, #8 . This feature will be added just before the production stage. We request you to follow our gitter channel for info like this. All these have been mentioned there earlier. I request you to go through it once.

Cheers,
Diwakar

**Comment by pranayyelugam** [comment]
@magician03 see this https://pranayyelugam.github.io/humble/. Is there any workaround about the mixed content issue ?

**Comment by magician03** [comment]
@pranayyelugam ,

#### Temp Fix
Allow unsafe scripts to load from chrome, by clicking on the shield symbol at the rightend of address bar.

#### Permanent fix
Use `https` protocol instead of `http` to fetch google web font stylesheet load.

Cheers,
Diwakar

**Comment by aswanthkoleri** [comment]
![screenshot from 2017-01-30 11 28 02](https://cloud.githubusercontent.com/assets/21339090/22413668/c99c7d5e-e6df-11e6-9fd1-abe8bc655ea0.png)
did u mean something like this (location of twitter feed will be changed)
