### ISSUE TITLE
Sitemap breakdown

### ISSUE THREAD

**Issue by magician03** [fossiiita/humblefoolcup#15]
Need to discuss the section wise breakdown of sitemap : 

Here are my thoughts:
* Landing viewport
* about | twitter feed
* time line
* content links | sponsors
* last year stats
* faq
* contact

Suggest your thoughts @gauthamzz @faheemzunjani @himanshub16 and others

**Comment by gauthamzz** [comment]
@magician03 i think faq should come before sponsors
and last year should have a seperate page for itself
and we need to dedicate one page for @humblefool the reason for this event

**Comment by magician03** [comment]
@gauthamzz , this needs to be finalised ASAP, what sections should be in the main page and what all should be made as separate pages. I request you to talk to other mentors and finalise this ASAP and theme/ color layout too.

Cheers,
Diwakar
