### ISSUE TITLE
Make a Tribute page for humblefool aka Harsha Suryanarayana

### ISSUE THREAD

**Issue by magician03** [fossiiita/humblefoolcup#16]
A tribute for humblefool needs to built and linked to the site. This will be a separate single static page.

Please mention about him quora answers can be used for [refrence](https://www.quora.com/Who-was-humblefool)

**Comment by pradeepgangwar** [comment]
I thing header of page will be like jubotron and then centered image of harsha suryanarayana and then three side by side dedicated columns for details about him. and then achievements below it and finally footer. and ofcourse a navbar copied from home page.

**Comment by magician03** [comment]
@pradeepgangwar , what you are saying is just slight modification of a starter template. We do not want a tribute to be like that. Late Harsha Suryanarayana is the one who started main stream competitive programming in India, and he being from IIITA means a lot to us. We want his page to a bit special and last forever, not only for this event. Think of something else, or you can take a look at tribute pages online for some inspiration. 

Cheers,
Diwakar

**Comment by magician03** [comment]
@pradeepgangwar has taken up this issue. Please share your progress regularly by hosting it on your github pages, so that we can suggest you at every step and your work wont go as waste. All the best.

**Comment by gauthamzz** [comment]
@magician03 I would suggest keeping this page, a competitive coding themed one. Maybe some code getting written in the back of the page or https://www.whoismrrobot.com/ this website , but more competitive coding related

**Comment by magician03** [comment]
@pradeepgangwar , as suggested by @gauthamzz , the tribute needs to be as geeky and nerdy as possible. Try your level best, share your progress here regularly

**Comment by magician03** [comment]
@pradeepgangwar , please share your current progress

**Comment by pradeepgangwar** [comment]
Progress can be tracked here.... :)

https://pradeepgangwar.github.io/Humblefool-Webpage/

**Comment by gauthamzz** [comment]
1. font size is too large 
2. please add a nav bar
3. add his youtube channel link

**Comment by pradeepgangwar** [comment]
@magician03  said to remove footer and navbar as this is tribute page. Topcoder profile link is working.

Rest issues will be solved.
