### ISSUE TITLE
Raleway font error

### ISSUE THREAD

**Issue by VamsiSangam** [fossiiita/humblefoolcup#19]
Roboto font isn't actually showing up because of the ```https``` error.

![capture](https://cloud.githubusercontent.com/assets/11662001/22175816/d4e3055c-e022-11e6-93bc-abfb3b671a4e.JPG)

The right-side window is the hosted repository where the fonts aren't activated due to the error. The left-side window is how the website must actually look like. Changing the link to ```https``` in [materialize.css](https://github.com/fossiiita/humblefoolcup/blob/master/css/materialize.css#L6) will do 😄

**Comment by VamsiSangam** [comment]
Oh sorry... It is the Raleway font error. Raleway font was added by @Anupam-dagar during his [addition of code](https://github.com/fossiiita/humblefoolcup/commit/f3749ef621dc87e1d0bd6c891c43d375cf28efcf) for the timeline. Isn't it wrong to edit materialize library itself? Shouldn't it be placed in the ```styles.css``` file? And we must choose between Raleway and Roboto.

**Comment by Anupam-dagar** [comment]
I am sorry for my mistake, I will keep a better look on my code from next time.

**Comment by VamsiSangam** [comment]
Chill bro. You could correct it in your next PR. Btw, that timeline looks fabulous 😄 👍

**Comment by Anupam-dagar** [comment]
Thankx sir. 😁😀

**Comment by gauthamzz** [comment]
@Anupam-dagar Could you make a pr for it ?

**Comment by Anupam-dagar** [comment]
Ok, making a pr for it.
