### ISSUE TITLE
Add about section

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/humblefoolcup#2]
Add about section for the humblefool cup. 

basic idea.

It is a 2-tier ACM ICPC styled team contest conducted in the memory of Harsha SuryaNarayana a.k.a Humblefool. The prelims is conducted online while those selected for the finals get an invitation for the finals conducted at IIITA. The winner is awarded the prestigious Humblefool cup.

Approx Prize: 40K

**Comment by aswinzz** [comment]
I would like to work on this

**Comment by gauthamzz** [comment]
you can start working on this, please tell if you face any problem

**Comment by magician03** [comment]
@aswinzz , please share your current progress

**Comment by aswinzz** [comment]
it is done sir @magician03

**Comment by aswinzz** [comment]
[Facebook Post](https://www.facebook.com/photo.php?fbid=1178442222253430&set=a.165748876856108.33202.100002629918599&type=3&theater)
![screenshot from 2017-01-23 15-18-08](https://cloud.githubusercontent.com/assets/25057819/22199316/5f9c9e20-e180-11e6-95fb-d3f1d7d33a1e.png)
