### ISSUE TITLE
Add FAQ section in the landing page

### ISSUE THREAD

**Issue by magician03** [fossiiita/humblefoolcup#25]
FAQ section needs to added after the sponsors section. FAQ content will be lorem ipsum for now add 5/6 question with short lorem text

**Comment by Anupam-dagar** [comment]
I would like to do it.

**Comment by gauthamzz** [comment]
@Anupam-dagar please finish this issue ASAP, and take up max 1-2 issues at a time

**Comment by pradeepgangwar** [comment]
The faq section can be made look better... with other styles... i will work for new style.
