### ISSUE TITLE
Add Contact details in footer

### ISSUE THREAD

**Issue by magician03** [fossiiita/humblefoolcup#26]
Footer needs to be modified:
- Team Page link needs to be added
- Aparoksha site link needs to be added
- Contact numbers of humblefool cup organisers needs to be added

**Comment by aswanthkoleri** [comment]
sir i would like to do this

**Comment by gauthamzz** [comment]
just put dummy name and numbers for organizers for now
put a link to team page ( will be added soon . so dummy too )
fest  link is https://aparoksha.iiita.ac.in/
