### ISSUE TITLE
Fix footer text.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossiiita/humblefoolcup#39]
Currently the footer text "Aparoksha Team page"  is neither in center nor towards right end.
Move it towards right to make it look better. 
(This is my contribution towards issue no. #58).

**Comment by gauthamzz** [comment]
you can work on this ,move it to the right

**Comment by gauthamzz** [comment]
@Anupam-dagar what is the progress on this ?

**Comment by Anupam-dagar** [comment]
I have fixed it.

**Comment by Anupam-dagar** [comment]
I was thinking to create pr after adding team page

**Comment by Anupam-dagar** [comment]
![screenshot from 2017-01-29 01-42-34](https://cloud.githubusercontent.com/assets/21174572/22399541/49cb2eac-e5c4-11e6-80bb-d15c6ae377e4.png)
This looks fine?

**Comment by gauthamzz** [comment]
if there is team page , no need of organisers 
delete that part
