### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/humblefoolcup#4]
We need a logo for humblefool cup.

Graphic designers are welcome to send pr.

Best will be awarded winner on 26 jan , You can make multiple entries also :)

Requirements 

But you need to post on social media ,Your entry for logo in opencode and post link here with hashtags #opencode #humblefool #geekhaveniiita #iiita

**Comment by tarunsinghal97** [comment]
I make a logo for humblefoolcup , but i don't understand where to send my logo?

**Comment by magician03** [comment]
@tarunsinghal97, you can upload it here in comment section and later, after a review by our moderators, you can send a pull request with logo file uploaded as logo.(whatever) . @gauthamzz will be reviewing the logo along with all other mentors :smile:

Cheers,
Diwakar

**Comment by tarunsinghal97** [comment]
![tarun](https://cloud.githubusercontent.com/assets/21240173/22096466/b877f810-de41-11e6-8704-61c97fa68960.jpg)

**Comment by gauthamzz** [comment]
@tarunsinghal97 we will decide the logo in this thread on 26 jan and finalise the best one :+1:

**Comment by tarunsinghal97** [comment]
So, should I send pull request ??

**Comment by gauthamzz** [comment]
No , at the end of 26 jan we will decide the winner and the winner will get 30 points :+1: you dont need to do anything more :smile: : We will contact you if any need :+1: But you need to post on social media :+1: Your entry for logo in opencode and post link here

**Comment by magician03** [comment]
@tarunsinghal97 , since this is programming event in the memory of Lord Humblefool, we want the logo to be as geeky as possible with some mention to the Lord. Could you modify the existing one to make it better according to the above suggestions ?

**Comment by tarunsinghal97** [comment]
I make a modified logo with photo o Lord humblefool and tried to add useful information.
Is it fine?
![humblefool](https://cloud.githubusercontent.com/assets/21240173/22174157/0dfc4a22-dffd-11e6-85d8-d35035dc42dd.png)

**Comment by gauthamzz** [comment]
@tarunsinghal97 i don't think his name and india's firwst redcoder part is needed. can you reduce the number of colors in the logo

**Comment by aswinzz** [comment]
![logo](https://cloud.githubusercontent.com/assets/25057819/22204487/3fe0382c-e198-11e6-922b-7ec02e862b6c.png)

**Comment by Siddhant2016** [comment]
![logo](https://cloud.githubusercontent.com/assets/20617436/22207023/874493b0-e1a3-11e6-8f6b-4887714f690c.jpg)
Please suggest required changes.
Siddhant Srivastav
