### ISSUE TITLE
link main website to tribute page

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/humblefoolcup#41]
see #40 we need to link this to main website while clicking the Humblefool in the main website.

**Comment by aswanthkoleri** [comment]
I'll do this

**Comment by gauthamzz** [comment]
please do this ASAP

**Comment by gauthamzz** [comment]
the code needs to be also shifted from humblefool folder to the main one as well.
the linked file is humblefool.html

**Comment by aswanthkoleri** [comment]
done @gauthamzz
