### ISSUE TITLE
add background

### ISSUE THREAD

**Issue by aswanthkoleri** [fossiiita/humblefoolcup#44]
As we all know that humblefoolcup has a plain whit  background. Add a good background to the humblefoolcup webpage . (This is my contribution to #58)

**Comment by gauthamzz** [comment]
@aswanthkoleri would you like to work on this ?

**Comment by aswanthkoleri** [comment]
yes , i'll do it .

**Comment by gauthamzz** [comment]
@aswanthkoleri what is the progress ?

**Comment by aswanthkoleri** [comment]
![screenshot from 2017-01-31 12 32 54](https://cloud.githubusercontent.com/assets/21339090/22455307/929289a2-e7b1-11e6-9787-0b254dcaeae8.png)
will this do .

**Comment by gauthamzz** [comment]
send pr @aswanthkoleri
