### ISSUE TITLE
Add a Header to the page 

### ISSUE THREAD

**Issue by aswanthkoleri** [fossiiita/humblefoolcup#48]
Currently the site Doesn't have a header .A proper header would be nice .

**Comment by gauthamzz** [comment]
It does have a header

**Comment by aswanthkoleri** [comment]
i mean a header with some background .

**Comment by aswinzz** [comment]
How about this?
![screenshot from 2017-01-30 18-14-43](https://cloud.githubusercontent.com/assets/25057819/22423510/015fd1e0-e718-11e6-9f28-5a3a9ee33a03.png)

**Comment by aswinzz** [comment]
any changes to be made?

**Comment by gauthamzz** [comment]
@aswinzz it looks great send pr
