### ISSUE TITLE
Landing ViewPort design

### ISSUE THREAD

**Issue by magician03** [fossiiita/humblefoolcup#5]
Landing viewport needs to be designed with logo, title, contest lists, nav bar, social buttons, sponsor logos

**Comment by magician03** [comment]
@gauthamzz , this issue needs to resolved ASAP.

**Comment by gauthamzz** [comment]
two rounds will be held one offline and one online in college . top 50 participants will be selected to the final round , which will be held in iiit allahabad. Dates are yet to be finalised

**Comment by anu-007** [comment]
@magician03 I like to work on it but first tell me how do you want it to look like give me an example.

**Comment by gauthamzz** [comment]
@anu-007 this issue will be solved by a series of other issues and hence has been broken down, you can work on other issues related to this for now
