### ISSUE TITLE
Add proper event timeline and give register link

### ISSUE THREAD

**Issue by pradeepgangwar** [fossiiita/humblefoolcup#58]
Since official date of first round of Humblefoolcup is declared. We should update this page ASAP and should give registration links. And all prize details should be included. If possible update the FAQ section too and change thhe welcome header background and text. looks like it doesnot match to other part of webpage

**Comment by gauthamzz** [comment]
you can work on these , aswanth is working on changing the color . everyhting else you can update and send pr asap

**Comment by pradeepgangwar** [comment]
Currently i cannot work on this..... but if u can wait till tomorrow then day after tommorow i can work for this.

**Comment by gauthamzz** [comment]
sorry we cant , i will do this myself

**Comment by Anupam-dagar** [comment]
I can do this if you allow me.
I am almost done with team page.

**Comment by aswanthkoleri** [comment]
can i do this ?
