### ISSUE TITLE
Add Sponsors section

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/humblefoolcup#6]
We need a sponsorship section like in hack in the north website

**Comment by aswanthkoleri** [comment]
the sponsorship section in the hack in the north website is included in the navbar but we dont have any contents in the navbar links

**Comment by gauthamzz** [comment]
you need to add sponsors in navabar and you need to make a sponsors section and in that section put a dummy logo for the time being.

**Comment by magician03** [comment]
@gauthamzz , this issue has been resolved and can be closed right now. Thanks for your contributions @VamsiSangam 

Cheers,
Diwakar
