### ISSUE TITLE
Add team page

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/humblefoolcup#7]
Team page should be separate.

**Comment by aswinzz** [comment]
sir i would like to work on this issue

**Comment by Anupam-dagar** [comment]
Sir the team page has been changed by me according to the materiize design. It just need some final review.

**Comment by gauthamzz** [comment]
this is already solved #30

**Comment by gauthamzz** [comment]
@Anupam-dagar show me

**Comment by Anupam-dagar** [comment]
![screenshot from 2017-01-24 01-09-48](https://cloud.githubusercontent.com/assets/21174572/22219736/fa69071c-e1d1-11e6-8960-6aee4483d1f6.png)
(Zoomed out view)
I will make the PR by tomorrow.

**Comment by gauthamzz** [comment]
Yeah this will work

**Comment by Anupam-dagar** [comment]
![check](https://cloud.githubusercontent.com/assets/21174572/22398120/fb77e870-e5a6-11e6-91a2-74a3dd2be02d.png)
will these work?

**Comment by gauthamzz** [comment]
@Anupam-dagar yeah sure they will

**Comment by magician03** [comment]
@Anupam-dagar , team page should look more or less like the main site. Ensure the default coloring scheme is followed and dont put the header background in the team page.
