### ISSUE TITLE
Change the default boilerplate ( if necessary )

### ISSUE THREAD

**Issue by magician03** [fossiiita/humblefoolcup#8]
Current boilerplate seems to be too low for students to work upon and develop. So anyone can suggest any new bare bones boilerplate for the kick start of development.

**Comment by pranayyelugam** [comment]
We could use Angular ( single page ) rather than using any boilerplate ,Moreover ,it works faster .

**Comment by magician03** [comment]
Hi @pranayyelugam ,

Thanks for your interst. By boiler plate, I mean the default site upon which participants can contribute. It is not any lang or stack. It can be of any stack. I preferred this particular one because

- Not everyone is familiar with latest JS frameworks( angular, react, etc )
- Would be a good and easy start for everyone to contribute.
- Angular or Advanced JS frameworks are preferred when we require instant rendering with rigorous data-flow among the DOM elements.

And we do not need Angular here, because this is intended to be a single page static site and there will no need for anything to render instantly and no data flow. You still can use angular, if you want to, providing, you can take care of the angular part, and use all/ most of its important features.

We can talk about this further, if you are willing to, and suggest some good and suitable angular boiler plate

Cheers,
Diwakar

**Comment by pradeepgangwar** [comment]
If by boilerplate we mean template design of webpage. Then can we choose from different templates available online.

**Comment by magician03** [comment]
@pradeepgangwar , yeah, we need to choose a basic bare bones template, and whats present right now serves the purpose. And if not this, we will be using bootstrap starter template. Not a big deal.

**Comment by magician03** [comment]
Default boilerplate changed to Materialize starter template, thanks everyone for their suggestions and contributions. Closing this issue.
