### ISSUE TITLE
Add links to Event and Event registration 

### ISSUE THREAD

**Issue by magician03** [fossiiita/humblefoolcup#9]

**Comment by gauthamzz** [comment]
I am closing this, since we havent finalised the platform yet

**Comment by magician03** [comment]
At least we shall put dummy links temporarily, after the development, it is difficult to find space in the site to hyperlink those, and before closing an issue, please wait for the confirmation of the one who created the issue.

Cheers,
Diwakar

**Comment by gauthamzz** [comment]
solved in #24
